services:
  - type: web
    name: e-learning-dsp
    env: static
    buildCommand: cd "E-Learning DSP/frontend" && npm install && npm run build
    staticPublishPath: ./E-Learning DSP/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
