name: unit tests
on:
  push

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: merge develop
        run: |
           git fetch origin
           git checkout origin/develop
           git checkout ${{ github.head_ref }}
           git -c user.email="bot@datasmartpoint.com" -c user.name="runner_script" merge origin/develop -m "merge for tests" --allow-unrelated-histories
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: |
          cd frontend
          npm ci
      - name: run vitest
        run: |
          cd frontend
          npm run test:run

